### ISSUE TITLE
Plugin not loading (1.18.1)

### ISSUE THREAD

**Issue by Zekariaa** [SentixDev/squaremarker#10]
```
[11:15:49] [Server thread/INFO]: [squaremarker] Enabling squaremarker v1.0.0
[11:15:49] [Server thread/ERROR]: Error occurred while enabling squaremarker v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
	at dev.sentix.squaremarker.Components.parse(Components.kt:10) ~[squaremarker-1.18.2-1.0.0.jar:?]
	at dev.sentix.squaremarker.command.commands.HelpCommand.register$lambda-0(HelpCommand.kt:20) ~[squaremarker-1.18.2-1.0.0.jar:?]
	at dev.sentix.squaremarker.command.CommandManager.registerSubcommand(CommandManager.kt:73) ~[squaremarker-1.18.2-1.0.0.jar:?]
	at dev.sentix.squaremarker.command.commands.HelpCommand.register(HelpCommand.kt:18) ~[squaremarker-1.18.2-1.0.0.jar:?]
	at dev.sentix.squaremarker.command.CommandManager.<init>(CommandManager.kt:53) ~[squaremarker-1.18.2-1.0.0.jar:?]
	at dev.sentix.squaremarker.SquareMarker.initCommandManager(SquareMarker.kt:51) ~[squaremarker-1.18.2-1.0.0.jar:?]
	at dev.sentix.squaremarker.SquareMarker.onEnable(SquareMarker.kt:21) ~[squaremarker-1.18.2-1.0.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:729) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:315) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.MiniMessage
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 18 more
[11:15:49] [Server thread/INFO]: [squaremarker] Disabling squaremarker v1.0.0
```

Was using 1.0.0 because others are not usable on 1.18.1.

**Comment by SentixDev** [comment]
Please try it with this version: 

https://github.com/SentixDev/Pl3xMap-Marker/releases/tag/release-4.1-squaremap

Also please keep in mind that 1.18.1 is outdated.
