### ISSUE TITLE
1.19.3 incompatibility

### ISSUE THREAD

**Issue by AndrewChqng** [SentixDev/squaremarker#12]
Hi, not sure if it's my side but thought I'd just file this in case you can help :)
```
[Server thread/ERROR]: Error occurred while enabling squaremarker v1.0.2 (Is it up to date?)
dev.sentix.lib.cloud.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: paper brigadier initialization failure (null)
        at dev.sentix.lib.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:134) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.squaremarker.paper.SquareMarkerPlugin.createCommandManager(SquareMarkerPlugin.kt:47) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.squaremarker.paper.SquareMarkerPlugin.onEnable(SquareMarkerPlugin.kt:23) ~[squaremarker-paper-1.0.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[squaremarker-paper-1.0.2.jar:?]
        ... 13 more
Caused by: java.lang.IllegalStateException: Could not find Registry Registry field
        at dev.sentix.lib.cloud.commandframework.bukkit.internal.RegistryReflection.lambda$static$2(RegistryReflection.java:71) ~[squaremarker-paper-1.0.2.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:71) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTy
pes.java:78) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[squaremarker-paper-1.0.2.jar:?]
        at dev.sentix.lib.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[squaremarker-paper-1.0.2.jar:?]
        ... 13 more
[23:10:37] [Server thread/INFO]: [squaremarker] Disabling squaremarker v1.0.2
[23:10:37] [Server thread/ERROR]: Error occurred while disabling squaremarker v1.0.2 (Is it up to date?)
dev.sentix.lib.kotlin.UninitializedPropertyAccessException: lateinit property squareMarker has not been initialized
        at dev.sentix.squaremarker.paper.SquareMarkerPlugin.onDisable(SquareMarkerPlugin.kt:36) ~[squaremarker-paper-1.0.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:403) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:587) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:378) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by jpenilla** [comment]
For updating the Paper plugin pretty sure we just need to update cloud to 1.8.0, will look at doing that when I have time

**Comment by wilkesreid** [comment]
Bump. Would love to be able to use this

**Comment by jpenilla** [comment]
https://github.com/SentixDev/squaremarker/actions/runs/3762443220

the artifacts zip here should contain a jar working on 1.19.3 (fabric and paper)

**Comment by AndrewChqng** [comment]
Yep thank you ran the latest artifact workflow at this time and all ran a-okay from what I can see

**Comment by jpenilla** [comment]
Gonna reopen this until either myself or @SentixDev creates a new release

**Comment by jpenilla** [comment]
https://github.com/SentixDev/squaremarker/releases/tag/1.19.3-v1.0.3
