### ISSUE TITLE
SquareMarker not working on Paper 1.21

### ISSUE THREAD

**Issue by UPSOKen** [SentixDev/squaremarker#30]
```
[12:58:54 ERROR]: Error occurred while enabling squaremarker v1.0.5 (Is it up to date?)
dev.sentix.lib.cloud.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: paper brigadier initialization failure (null)
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:143) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.squaremarker.paper.SquareMarkerPlugin.createCommandManager(SquareMarkerPlugin.kt:48) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.squaremarker.paper.SquareMarkerPlugin.onEnable(SquareMarkerPlugin.kt:23) ~[squaremarker-paper.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:83) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:76) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:72) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:137) ~[squaremarker-paper.jar:?]
        ... 14 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.resources.ResourceLocation.<init>(java.lang.String)
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.CraftBukkitReflection.needConstructor(CraftBukkitReflection.java:181) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:54) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:83) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:76) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:72) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:137) ~[squaremarker-paper.jar:?]
        ... 14 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.resources.ResourceLocation.<init>(java.lang.String)
        at java.base/java.lang.Class.getConstructor0(Class.java:3784) ~[?:?]
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2955) ~[?:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.CraftBukkitReflection.needConstructor(CraftBukkitReflection.java:179) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:54) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:83) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:76) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:72) ~[squaremarker-paper.jar:?]
        at squaremarker-paper.jar/dev.sentix.lib.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:137) ~[squaremarker-paper.jar:?]
        ... 14 more
[12:58:54 INFO]: [squaremarker] Disabling squaremarker v1.0.5
[12:58:54 ERROR]: Error occurred while disabling squaremarker v1.0.5
dev.sentix.lib.kotlin.UninitializedPropertyAccessException: lateinit property squareMarker has not been initialized
        at squaremarker-paper.jar/dev.sentix.squaremarker.paper.SquareMarkerPlugin.onDisable(SquareMarkerPlugin.kt:36) ~[squaremarker-paper.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

Any ideas? I use this plugin extensively.

**Comment by UPSOKen** [comment]
Pastebin version: [https://pastebin.com/5CButvZ7](https://pastebin.com/5CButvZ7)

**Comment by jpenilla** [comment]
https://github.com/SentixDev/squaremarker/actions/runs/9666777561/artifacts/1637077793 Use the dev build from the GH actions artifact for now.
